from pydantic import BaseModel, Field, EmailStr
from datetime import datetime


class Item(BaseModel):
    email: EmailStr
    username: str = Field(..., example="JohnDoe", description="The username of the user")
    description: str
    questions: str
    script: str = Field(..., description="The script generated by LLM system")
    