from pydantic import BaseModel, Field, EmailStr
from datetime import datetime


class Item(BaseModel):
    email: EmailStr
    username: str = Field(..., example="JohnDoe", description="The username of the user")
    description: str
    questions: str
    script: str = Field(..., description="The script generated by LLM system")
    

class PersonalData(BaseModel):
    linkdin_url: str = Field(..., 
                             description='linkdin url of applicant'
                             )
    github_url: str = Field(..., 
                            description="github url of applicant"
                            )
    personal_writeup: str = Field(..., description="a writeup of personal information of the applicant")
    job_post: str
    resume: str
