research_jobs:
  description: >
    Analyze the job post provided ::<JOB_POST> ({job_post}) </JOB_POST> to extract key skills, experiences, and qualifications required. 
    Analyze the company who posted the job to understand their background and what they would expect from a candidate.
    Use the tools to gather content and identify and categorize the requirements.

  expected_output: >
    A structured list of job requirements, including necessary skills, qualifications, and experiences
    and a summary of the company's background and expectations from a candidate.


create_personal_profile:
  description: >
    Compile a detailed personal and professional profile using the GitHub ({github_url}) URLs, 
    personal write-up ({personal_writeup}), gather profile information from user linkdin {linkdin_url} URL.
    Use the provided resume {resume} to extract additional information on skills and experiences.
    Utilize tools to extract and synthesize information from these sources.

  expected_output: >
    A comprehensive profile document that includes skills, project experiences, contributions, interests, and communication style.


create_resume_strategy:
  description: >
    Using the profile and job requirements obtained from previous tasks and using the provided resume {resume}, tailor the resume to highlight the most relevant areas. 
    Employ tools to adjust and enhance the resume content. Make sure this is the best resume even but don't make up any information. Update every section, 
    inlcuding the initial summary, work experience, skills, projects and education. All to better reflect the candidates abilities and how it matches the job posting.
    Make sure that you have not added any false information and do not make things up.
    reflect on whether the resume is improved compared with the provided resume.

  expected_output: >
    An updated resume that is tailored to the job requirements, highlighting the most relevant skills, experiences, and qualifications. 


interview_preperation_task:
  description: >
    Create a set of potential interview questions and talking points based on the tailored resume and job requirements. 
    Utilize tools to generate relevant questions and discussion points, reflect on whether the questions generated can fully asses the candidate. 
    Make sure to use these question and talking points to help the candiadte highlight the main points of the resume and how it matches the job posting.

  expected_output: >
    A document containing key questions and talking points that the candidate should prepare for the initial interview.


quality_control:
  description: >
    The AI CV Quality Control Agent is designed to enhance and optimize resumes for job applications. Leveraging advanced algorithms and machine learning, this AI agent performs the following tasks:
    ATS Compatibility Check: Analyzes the CV to ensure it is formatted correctly for Applicant Tracking Systems, increasing the likelihood of passing initial automated screenings.
    Content Quality Analysis: Evaluates the content for clarity, relevance, and impact, ensuring that key skills and experiences are effectively highlighted.
    Grammar and Style Review: Checks for grammatical errors, stylistic consistency, and overall readability, making the CV polished and professional.
    Keyword Optimization: Identifies and suggests relevant keywords and phrases based on the job description, enhancing the CV's alignment with specific job requirements.
    Feedback and Recommendations: Provides actionable feedback and recommendations for improvements, helping candidates refine their CVs to better fit the job market.
    This AI agent serves as a comprehensive tool for job seekers aiming to create standout CVs that meet both human and automated recruiter standards.

  expected_output: >
    An updated resume that has been optimized for ATS compatibility, content quality, grammar and style, keyword optimization, and overall quality. only provide the CV no need any comments.
